-- CreateTable
CREATE TABLE "Lemonsqueezy" (
    "id" TEXT NOT NULL,
    "order_id" INTEGER NOT NULL,
    "tax" DECIMAL(65,30) NOT NULL,
    "receipt_url" TEXT NOT NULL,
    "total" DECIMAL(65,30) NOT NULL,
    "status" TEXT NOT NULL,
    "tax_usd" DECIMAL(65,30) NOT NULL,
    "currency" TEXT NOT NULL,
    "refunded" BOOLEAN NOT NULL,
    "store_id" DECIMAL(65,30) NOT NULL,
    "subtotal" DECIMAL(65,30) NOT NULL,
    "tax_name" TEXT NOT NULL,
    "tax_rate" DECIMAL(65,30) NOT NULL,
    "setup_fee" DECIMAL(65,30) NOT NULL,
    "test_mode" BOOLEAN NOT NULL,
    "total_usd" DECIMAL(65,30) NOT NULL,
    "user_name" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL,
    "identifier" TEXT NOT NULL,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "user_email" TEXT NOT NULL,
    "customer_id" DECIMAL(65,30) NOT NULL,
    "refunded_at" TEXT,
    "order_number" DECIMAL(65,30) NOT NULL,
    "subtotal_usd" DECIMAL(65,30) NOT NULL,
    "currency_rate" TEXT NOT NULL,
    "setup_fee_usd" DECIMAL(65,30) NOT NULL,
    "tax_formatted" TEXT NOT NULL,
    "tax_inclusive" BOOLEAN NOT NULL,
    "discount_total" DECIMAL(65,30) NOT NULL,
    "refunded_amount" DECIMAL(65,30) NOT NULL,
    "total_formatted" TEXT NOT NULL,
    "status_formatted" TEXT NOT NULL,
    "discount_total_usd" DECIMAL(65,30) NOT NULL,
    "subtotal_formatted" TEXT NOT NULL,
    "refunded_amount_usd" DECIMAL(65,30) NOT NULL,
    "setup_fee_formatted" TEXT NOT NULL,
    "discount_total_formatted" TEXT NOT NULL,
    "refunded_amount_formatted" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,

    CONSTRAINT "Lemonsqueezy_pkey" PRIMARY KEY ("id")
);
